spring:
  datasource:
    url: jdbc:mysql://${MY_HOST:localhost}:${MY_PORT:5431}/${DB_NAME:carRental}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:123456}
  jpa:
    generate-ddl: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

secret:
  secret-key: ${SECRET_JWT_KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 864000000
server:
  servlet:
    context-path: /api

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

pay-os:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}